spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
        - id: author-service
          uri: lb://author-service
          predicates:
              - Path=/api/v1/authors/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
