spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - name: AuthenticationFilter
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - name: AuthenticationFilter
        - id: author-service
          uri: lb://author-service
          predicates:
            - Path=/api/v1/authors/**
          filters:
            - name: AuthenticationFilter
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - name: AuthenticationFilter
      discovery:
        locator:
          enabled: true
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  tracing:
    sampling:
      probability: 1.0
jwt:
  Secret-Key: mYiADZOy9Hq5pTfomhj9hPUJLGAN/ZB6AZ4yoHfCtN0f8DaNQr6+4qeaJ9YfMK4ZbX85J3ao6TotW+jrLKLGeafpaYYLn2mmrYOB/1mJzhQYEaf883PtWAIwnTwHpPuEsJAhyHwEtlTvy++pZA+0bns66RUDBk80bJUA4JhJUI8
  Expiration-Time: 60